title: SLICE
description: >
  A FEASTorg project page for SLICE.
baseurl: "/SLICE_DCMT"
url: "https://feastorg.github.io"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM

# Don't publish these
exclude:
  - TODO.md
  - .indexignore

# automatically apply layout: page to all docs/*.md
defaults:
  - scope:
      path: "" # everything under docs/
      type: "pages"
    values:
      layout: "page"
