title: Slice_DCMT
description: >
  A FEASTorg project page for SLICE.
baseurl: "/Slice_DCMT"
url: "https://feastorg.github.io"

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  input: GFM

# Don't publish these
exclude:
  - TODO.md
  - .indexignore

# automatically apply layout: page to all docs/*.md
defaults:
  - scope:
      path: "" # everything under docs/
      type: "pages"
    values:
      layout: "page"
