name: Generate main docs index

on:
  workflow_call:

permissions:
  contents: write

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { persist-credentials: true }
      - uses: actions/setup-python@v4
        with: { python-version: "3.x" }
      - name: Generate all docs/index.md
        run: python scripts/generate_docs_index.py
