name: Generate main docs index

on:
  workflow_call:

permissions:
  contents: write

concurrency:
  group: gen-main-index
  cancel-in-progress: true

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      # Always start from the latest remote main (clean tree)
      - name: Sync to latest main
        run: |
          git fetch origin main
          git checkout -B main origin/main

      - uses: actions/setup-python@v4
        with: { python-version: "3.x" }

      - name: Generate all docs/index.md
        run: python scripts/generate_docs_index.py

      - name: Commit & push (safe rebase)
        run: |
          set -e
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          git add docs/index.md
          if git diff --cached --quiet; then
            echo "✅ No changes to commit."
            exit 0
          fi

          git commit -m "🔁 Auto-generate docs index"
          # Rebase our new commit onto latest remote (handles races)
          git fetch origin main
          git pull --rebase origin main
          git push origin HEAD:main
