name: Generate main docs index

on:
  workflow_call:

permissions:
  contents: write

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Sync to latest main
        run: |
          git fetch origin main
          git checkout -B main origin/main

      - uses: actions/setup-python@v4
        with: { python-version: "3.x" }

      - name: Generate all docs/index.md
        run: python scripts/generate_main_index.py

      - name: Commit & push (rebase if needed)
        run: |
          set -e
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"
          if ! git diff --quiet -- docs; then
            git add docs
            git commit -m "🔁 Auto-generate docs index"
            git push origin HEAD:main || (git -c rebase.autoStash=true pull --rebase origin main && git push origin HEAD:main)
          else
            echo "✅ Indexes up to date"
          fi
