name: KiBot CI/CD

permissions:
  contents: read
  actions: write

on:
  push:
    paths:
      - "_config.yml"
      - "hardware/**"
      - ".github/workflows/**"
      - "docs/**"
  pull_request:
    paths:
      - "_config.yml"
      - "hardware/**"
      - ".github/workflows/**"
      - "docs/**"
  schedule:
    # Run at 05:43 UTC every Wednesday
    - cron: "43 5 * * 3"

env:
  OUT_DIR: Generated

jobs:
  ERC:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto:latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run ERC
        run: |
          ls -la hardware/
          make -C hardware/ erc

  DRC:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto:latest
    needs: ERC
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          
      - name: Run DRC
        run: make -C hardware/ drc

  Fab:
    name: Generate All Fabrication Outputs
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto_full:latest
    needs: [DRC, ERC]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Generate SCH files
        run: make -C hardware/ sch_fab
      - name: Generate PCB Fab Files
        run: make -C hardware/ pcb_fab
      - name: Upload all KiBot output
        uses: actions/upload-artifact@v4
        with:
          name: kibot-site
          path: hardware/${{ env.OUT_DIR }}
