name: KiBot CI/CD + Deploy to GitHub Pages

permissions:
  contents: read
  actions: write
  pages: write
  id-token: write

on:
  push:
    paths:
      - "_config.yml"
      - "hardware/**"
      - ".github/workflows/**"
      - "docs/**"
  pull_request:
    paths:
      - "_config.yml"
      - "hardware/**"
      - ".github/workflows/**"
      - "docs/**"
  schedule:
    - cron: "43 5 * * 3"

jobs:
  ERC:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto:latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Run ERC
        run: make -C hardware/ erc

  DRC:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto:latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Run DRC
        run: make -C hardware/ drc

  Fab:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto_full:latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install yq
        run: |
          apt-get update
          apt-get install -y yq

      - name: Load project config
        id: config
        run: |
          OUT_DIR=$(yq '.output_dir' docs/site_config.yml)
          echo "out_dir=$OUT_DIR" >> $GITHUB_OUTPUT

      - name: Generate SCH files
        run: make -C hardware/ sch_fab
      - name: Generate PCB Fab Files
        run: make -C hardware/ pcb_fab

      - name: Upload KiBot Outputs
        uses: actions/upload-artifact@v4
        with:
          name: kibot-site
          path: hardware/${{ steps.config.outputs.out_dir }}

  pages:
    needs: Fab
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y yq

      - name: Load project config
        id: config
        run: |
          PROJECT_NAME=$(yq '.project_name' docs/site_config.yml)
          OUT_DIR=$(yq '.output_dir' docs/site_config.yml)
          echo "project_name=$PROJECT_NAME" >> $GITHUB_OUTPUT
          echo "out_dir=$OUT_DIR" >> $GITHUB_OUTPUT

      - name: Download KiBot artifacts
        uses: actions/download-artifact@v5
        with:
          name: kibot-site
          path: _downloads

      - name: Copy selected KiBot outputs
        run: |
          mkdir -p docs
          cp _downloads/Schematic.pdf docs/
          cp _downloads/PCB.pdf docs/
          cp _downloads/kibot.log docs/

      - name: Generate index.md from template
        run: |
          DATE=$(date '+%Y-%m-%d')
          PROJECT_NAME="${{ steps.config.outputs.project_name }}"
          ARTIFACTS=$(yq '.artifacts[]' docs/site_config.yml)

          LINKS=""
          for f in $ARTIFACTS; do
            LINKS="$LINKS- [$f](./$f)\n"
          done

          cat docs/index_template.md \
            | sed "s|{{project_name}}|$PROJECT_NAME|g" \
            | sed "s|{{date}}|$DATE|g" \
            | sed "s|{{output_links}}|$LINKS|g" \
            > docs/index.md

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/

  deploy:
    needs: pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
